version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database:
    image: postgres:latest
    env_file:
      - deduce/.env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume