# Generated by Django 3.0.4 on 2020-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
