# Generated by Django 3.0.4 on 2020-03-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeduceUser',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('last_anstime', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Deduce Users',
                'ordering': ['-level', 'last_anstime'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_number', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200)),
                ('question', models.TextField(null=True)),
                ('level_file', models.FileField(blank=True, null=True, upload_to='level_images/')),
                ('filetype', models.CharField(blank=True, choices=[('I', 'Image'), ('NI', 'Not Image')], default='Image', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Level')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('answer', models.TextField()),
                ('anstime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DeduceUser')),
            ],
        ),
    ]
