# Generated by Django 3.0.4 on 2020-03-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200324_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-level', 'last_anstime']},
        ),
    ]
