# Generated by Django 3.0.4 on 2020-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200324_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
