# Generated by Django 3.0.4 on 2020-04-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200325_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.Level'),
        ),
    ]
