# Generated by Django 3.0.4 on 2020-04-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200415_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level_file',
            new_name='level_file_1',
        ),
        migrations.RemoveField(
            model_name='level',
            name='filetype',
        ),
        migrations.AddField(
            model_name='level',
            name='level_file_2',
            field=models.FileField(blank=True, null=True, upload_to='level_images/'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_file_3',
            field=models.FileField(blank=True, null=True, upload_to='level_images/'),
        ),
        migrations.AddField(
            model_name='level',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
