# Generated by Django 3.0.4 on 2020-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200415_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='cover_image',
            field=models.FileField(default='', upload_to='cover_images/'),
            preserve_default=False,
        ),
    ]
