# Generated by Django 3.0.4 on 2020-04-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200417_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
