# Generated by Django 3.0.4 on 2020-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_currentlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlevel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
