# Generated by Django 3.0.4 on 2020-05-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerLog',
        ),
    ]
