# Generated by Django 3.0.4 on 2020-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_answerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlevel',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
