# Generated by Django 3.0.4 on 2020-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_currentlevel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
