# Generated by Django 3.0.4 on 2020-06-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_level_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlevel',
            name='user',
        ),
    ]
