# Generated by Django 3.0.4 on 2020-06-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_currentlevel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlevel',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
